### PR TITLE
Handle parse_event_xml doing I/O in the event loop

### PR DESCRIPTION
**Pull request by bdraco**
Fixes https://github.com/home-assistant/core/issues/48732

I'll update the SoCo PR as well : https://github.com/SoCo/SoCo/pull/815

### CODE REVIEW

**Comment by amelchio** [comment]
Oh, good thing I admitted to not reviewing :-P. Just let me know when you are ready to have it pushed out.

**Comment by bdraco** [comment]
> Oh, good thing I admitted to not reviewing :-P. Just let me know when you are ready to have it pushed out.

👍 . I've been extra vigilant about testing but I didn't expect `parse_event_xml` to trigger discovery or I/O!

**Comment by amelchio** [comment]
Yeah, SoCo is odd like that. Most properties will also request data from the speaker.

**Comment by cgtobi** [comment]
Looks like it fixed the problem.

**Comment by bdraco** [comment]
Looks good on my end as well

**Comment by amelchio** [comment]
0.0.42 published 😊

**Comment by bdraco** [comment]
Thanks. I'll bump core

**Pull request merged**
