### PR TITLE
Add events_asyncio events module

### PR DESCRIPTION
**Pull request by bdraco**
- aiohttp is used for the events server
- subscriptions subscribe/unsubscribe/renew now return awaitables

### CODE REVIEW

**Comment by amelchio** [comment]
Great, I have been wanting to look into that but didn't find the time.

Would you mind also submitting to SoCo, maintenance is easier if I can just merge from them :)

**Comment by bdraco** [comment]
> Great, I have been wanting to look into that but didn't find the time.
> 
> Would you mind also submitting to SoCo, maintenance is easier if I can just merge from them :)

👍  Will do when I finish cleaning it up.  Right now it is functional but a bit messy....but tomorrow since its late late late here.

**Comment by bdraco** [comment]
TODOS:

**Comment by bdraco** [comment]
TODOS:


- [x] Implement `strict` correctly
- [x] Docs and comments with example
- [x] ClientSession cleanup (can we use the shared one... probably not)
- [x] Audit for threading.Lock
- [x] Testing

**Comment by bdraco** [comment]
I can't think of anything else to test.  It would be great to get another set of eyes.

cc @cgtobi

**Comment by bdraco** [comment]
When this looks good, I'll open something with `SoCo` as well.

**Review by amelchio — APPROVED** [review]
Full disclosure, I did not review this because I think that is better done upstream.

But I am willing to merge it as is, in fact the purpose of this project is to ship work that is not yet merged into SoCo. I have also found that a little time in Home Assistant can reveal bugs that can be fixed before submitting to SoCo.

So just let me know what you want to do :)

**Comment by bdraco** [comment]
> Full disclosure, I did not review this because I think that is better done upstream.
> 
> But I am willing to merge it as is, in fact the purpose of this project is to ship work that is not yet merged into SoCo. I have also found that a little time in Home Assistant can reveal bugs that can be fixed before submitting to SoCo.
> 
> So just let me know what you want to do :)

That's similar to what I was thinking as I've tested this as far as I can go with the two Sonos systems that I have. We will have a whole month for this to get feedback in Home Assistant. I'll send any updates if there is anything that needs to be tweaked here, and once we push though next beta cycle, I'll open the PR to `SoCo` knowing that its solid.

**Comment by amelchio** [comment]
All right, I published 0.0.41 with this PR. Thank you!

**Comment by bdraco** [comment]
Thank you 👍

**Pull request merged**
