### PR TITLE
Lists 'sonos amp' as a soundbar in order to provide night mode and speech enhancement support for amp.

### PR DESCRIPTION
**Pull request by iainp999**
Fixes #35740.

https://github.com/home-assistant/core/issues/35740

### CODE REVIEW

**Comment by iainp999** [comment]
@amelchio I have opened a PR on SoCo for this, so closing this one.

https://github.com/SoCo/SoCo/pull/721

**Comment by amelchio** [comment]
It's great that you submit upstream but we can merge here anyway ... SoCo releases can be far between.

**Comment by iainp999** [comment]
OK, np @amelchio - that's great.  I am quite keen to get the change in so I can update HA without losing my mods :)

**Comment by amelchio** [comment]
This should make it to Home Assistant 0.110 via home-assistant/core#35793

**Pull request merged**
