### PR TITLE
Support Spotify podcasts and podcast episodes in URL/URI detection

### LINKED ISSUE #73: Support Spotify URL’s/URI’s for podcasts and podcast episodes (“show”/“episode”)
#66 added support to detect Spotify URLs and URIs. This feature could be extended to handle podcasts, e.g.

- https://open.spotify.com/show/5d0T55VOxfqMBzi6Pw5Xam
- https://open.spotify.com/episode/1TDhV6dwkZyPbpg56OxDMW

### PR DESCRIPTION
**Pull request by mountainsandcode**
Fixes #73

### CODE REVIEW

**Comment by amelchio** [comment]
Thanks for working on this!

Did you test that it works? I don't see how it could, without also adding those types to `spotify_magic`?

**Comment by mountainsandcode** [comment]
> Thanks for working on this!
> 
> Did you test that it works? I don't see how it could, without also adding those types to `spotify_magic`?

Excellent point, I missed that. 

Was doing in on an iPad thinking it was a quick fix, let me try to do this properly next week when I’m back at a laptop!

**Comment by mountainsandcode** [comment]
Unfortunately, this is more difficult than anticipated. The support is currently missing on the Sonos side.

**Comment by amelchio** [comment]
All right, thanks for getting back.

**Pull request closed without merging**
